image: ubuntu

variables:
    CC: gcc-7
    CXX: g++-7

before_script:
    - apt-get update -qq && apt-get install -y -qq cmake gcc-7 g++-7 libsdl2-dev
    - g++ --version && cmake --version

myapp:
    stage: build
    script:
        - git clean -df
        - cmake hello_world/
        - cmake --build .
        - ./hello
