image: ubuntu

variables:
    CC: gcc-7
    CXX: g++-7

before_script:
    - apt-get update -qq && apt-get install -y -qq cmake gcc-7 g++-7 libsdl2-dev
    - g++ --version && cmake --version

hello_world:
    stage: build
    script:
        - mkdir build/
        - cd build/
        - cmake ../hello_world/
        - cmake --build .
        - ./hello
        - cd ..
        - rm -rf build/

hello_libs:
    stage: build
    script:
        - mkdir build/
        - cd build/
        - cmake ../hello_libs/
        - cmake --build .
        - ./hello_bins/hello_bins
        - cd ..
        - rm -rf build/

sdl-dynamic-linking:
    stage: build
    script:
        - mkdir build/
        - cd build/
        - cmake ../sdl-dynamic-linking/
        - cmake --build .
        - ./sdl-dynamic-linking
        - cd ..
        - rm -rf build/

sdl-static-linking:
    stage: build
    script:
        - mkdir build/
        - cd build/
        - cmake ../sdl-static-linking/
        - cmake --build .
        - ./sdl-static-linking
        - cd ..
        - rm -rf build/

sdl-loop:
    stage: build
    script:
        - mkdir build/
        - cd build/
        - cmake ../sdl-loop/
        - cmake --build .
        #- ./sdl-loop
        - cd ..
        - rm -rf build/

basic-render:
    stage: build
    script:
        - mkdir build/
        - cd build/
        - cmake ../basic-render/
        - cmake --build .
        - ./basic-render
        - cd ..
        - rm -rf build/
