language: cpp
compiler: g++
sudo: required
dist: trusty
matrix:
  fast_finish: true
  include:
    - os: linux
      addons: &1
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - g++-mingw-w64
            - gcc-7
            - gcc-mingw-w64
            - libpython3.5-dev
            - python3.5-dev
      env:
        - CMAKE_VERSION="3.12.1"
        - CMAKE_GENERATOR="Unix Makefiles"
        - BUILDFLAGS="VERBOSE=1"


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - ./cmake.sh

script:
  - git clean -df
  - cmake hello_world/
  - make
  - ./hello

  - git clean -df
  - cmake hello_libs/
  - make
  - ./hello_bins/hello_bins
