dist: trusty
sudo: false

language: cpp

os: linux
compiler: gcc

addons: &gcc7
      apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           #- gcc-7
           - g++-7
           #- libsdl2-dev

env: COMPILER='g++-7' BUILD_TYPE='Debug'

install:
  #- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  #- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  #- |
  #  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
  #    CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz"
  #    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  #    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  #  fi
# Current loc is: /home/travis/build/OneWhiteSpirit/gamedev_courses/deps/cmake/bin/cmake
  - cd ${DEPS_DIR}/
  - cd ..
  - ls
  #- ./cmake.sh

before_script:
  - export CXX=${COMPILER}

script:
  - g++ -v && cmake --version

  - git clean -df
  - cmake hello_world/
  - cmake --build .
  - ./hello

  - git clean -df
  - cmake hello_libs/
  - cmake --build .
  - ./hello_bins/hello_bins
