dist: trusty
sudo: require
#sudo: false

language: cpp

os: linux
compiler: gcc

env: COMPILER='g++-7' BUILD_TYPE='Debug'

before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt-get install -qq libsdl2-dev
#  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
#  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
#  - |
#    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
#      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz"
#      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
#      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
#      #sudo ln -s ${DEPS_DIR}/cmake/bin/cmake /usr/local/bin/cmake
#    fi
# Current loc is: /home/travis/build/OneWhiteSpirit/gamedev_courses/deps/cmake/bin/cmake
#  - cd ${TRAVIS_BUILD_DIR}/
#  - pwd

before_script:
  - export CXX=${COMPILER}
  - sudo apt

script:
  - g++ -v && cmake --version

  - git clean -df
  - pwd
  - cmake ${TRAVIS_BUILD_DIR}/hello_world/
  - cmake --build .
  - ./hello

  - git clean -df
  - cmake ${TRAVIS_BUILD_DIR}/hello_libs/
  - cmake --build .
  - ./hello_bins/hello_bins

  - git clean -df
  - cmake ${TRAVIS_BUILD_DIR}/sdl-dynamic-linking/
  - cmake --build .
  - ./sdl-dynamic-linking
