language: cpp
compiler: g++
sudo: required
dist: trusty
matrix:
  fast_finish: true
  include:
    - os: linux
      addons: &1
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - g++-mingw-w64
            - gcc-7
            - gcc-mingw-w64
      env:
        - CMAKE_VERSION="3.12.1"
        - CMAKE_GENERATOR="Unix Makefiles"
        - BUILDFLAGS="VERBOSE=1"


before_install:
  - wget -O cmake.sh https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: true

script:
  - git clean -df
  - cmake hello_world/
  - make
  - ./hello

  - git clean -df
  - cmake hello_libs/
  - make
  - ./hello_bins/hello_bins
