dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
      apt:
         sources:
           - ubuntu-toolchain-r-test
           - sourceline: 'ppa:adrozdoff/cmake'
         packages:
           - gcc-7
           - g++-7
           - libsdl2-dev
           - cmake

install:
  - sudo apt-get update -qq

script:

  - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++

  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7

  - gcc -v && g++ -v && cmake --version

  - git clean -df
  - cmake hello_world/
  - cmake --build .
  - ./hello

  - git clean -df
  - cmake hello_libs/
  - cmake --build .
  - ./hello_bins/hello_bins
